# Generated by Django 3.2 on 2021-05-06 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_sports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('sports', models.CharField(max_length=40)),
                ('post', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Player_female',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('sports', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Player_Male',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=40)),
                ('sports', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='athletics_female',
            fields=[
                ('athletics_female_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_female')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='athletics_male',
            fields=[
                ('athletics_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='badminton_female',
            fields=[
                ('badminton_female_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_female')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='badminton_male',
            fields=[
                ('badminton_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='basketball_female',
            fields=[
                ('basketball_female_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_female')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='basketball_male',
            fields=[
                ('basketball_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='chess_female',
            fields=[
                ('chess_female_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_female')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='chess_male',
            fields=[
                ('chess_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='cricket_female',
            fields=[
                ('cricket_female_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_female')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='cricket_male',
            fields=[
                ('cricket_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='football_female',
            fields=[
                ('football_female_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_female')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='football_male',
            fields=[
                ('football_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='table_tennis_female',
            fields=[
                ('table_tennis_female_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_female')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='table_tennis_male',
            fields=[
                ('table_tennis_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('team_no', models.IntegerField()),
                ('result', models.CharField(max_length=40)),
                ('performance', models.CharField(max_length=40)),
            ],
        ),
    ]
