# Generated by Django 3.2 on 2021-05-06 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportocrats', '0002_alter_player_male_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_male',
            name='sid',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(21000000), django.core.validators.MinValueValidator(17000000)]),
        ),
    ]
