# Generated by Django 3.2 on 2021-05-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportocrats', '0003_alter_player_male_sid'),
    ]

    operations = [
        migrations.CreateModel(
            name='screening_athletics_male',
            fields=[
                ('screening_athletics_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('qualified', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='screening_badminton_male',
            fields=[
                ('screening_badminton_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('qualified', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='screening_basketball_male',
            fields=[
                ('screening_basketball_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('qualified', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='screening_chess_male',
            fields=[
                ('screening_chess_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('qualified', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='screening_cricket_male',
            fields=[
                ('screening_cricket_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('qualified', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='screening_football_male',
            fields=[
                ('screening_football_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('qualified', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='screening_table_tennis_male',
            fields=[
                ('screening_table_tennis_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.player_male')),
                ('qualified', models.CharField(max_length=40)),
            ],
        ),
    ]
