# Generated by Django 3.2 on 2021-05-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportocrats', '0004_screening_athletics_male_screening_badminton_male_screening_basketball_male_screening_chess_male_scr'),
    ]

    operations = [
        migrations.CreateModel(
            name='selection_athletics_male',
            fields=[
                ('selection_athletics_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.athletics_male')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='selection_badminton_male',
            fields=[
                ('selection_badminton_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.badminton_male')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='selection_basketball_male',
            fields=[
                ('selection_basketball_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.basketball_male')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='selection_chess_male',
            fields=[
                ('selection_chess_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.chess_male')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='selection_cricket_male',
            fields=[
                ('selection_cricket_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.cricket_male')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='selection_football_male',
            fields=[
                ('selection_football_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.football_male')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='selection_table_tennis_male',
            fields=[
                ('selection_table_tennis_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.table_tennis_male')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
    ]
