# Generated by Django 3.2 on 2021-05-11 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportocrats', '0005_selection_athletics_male_selection_badminton_male_selection_basketball_male_selection_chess_male_sel'),
    ]

    operations = [
        migrations.CreateModel(
            name='selection_badminton_female',
            fields=[
                ('selection_badminton_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.badminton_male')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='selection_chess_female',
            fields=[
                ('selection_chess_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.chess_male')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='selection_table_tennis_female',
            fields=[
                ('selection_table_tennis_male_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.table_tennis_male')),
                ('status', models.CharField(max_length=40)),
            ],
        ),
    ]
