# Generated by Django 3.2 on 2021-05-11 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportocrats', '0006_selection_badminton_female_selection_chess_female_selection_table_tennis_female'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection_chess_female',
            name='selection_chess_male_id',
        ),
        migrations.AddField(
            model_name='selection_chess_female',
            name='selection_chess_female_id',
            field=models.OneToOneField(default=1234, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.chess_female'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selection_badminton_female',
            name='selection_badminton_male_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.badminton_female'),
        ),
        migrations.AlterField(
            model_name='selection_table_tennis_female',
            name='selection_table_tennis_male_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sportocrats.table_tennis_female'),
        ),
    ]
