# Generated by Django 3.2 on 2021-05-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportocrats', '0007_auto_20210511_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selection_badminton_female',
            old_name='selection_badminton_male_id',
            new_name='selection_badminton_female_id',
        ),
        migrations.RenameField(
            model_name='selection_table_tennis_female',
            old_name='selection_table_tennis_male_id',
            new_name='selection_table_tennis_female_id',
        ),
    ]
