# Generated by Django 3.2 on 2021-05-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportocrats', '0008_auto_20210511_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='sports_equipments',
            fields=[
                ('sports_equipments_id', models.AutoField(primary_key=True, serialize=False)),
                ('sports_name', models.CharField(max_length=40)),
                ('no_of_qty_available', models.CharField(max_length=40)),
                ('no_of_qty_required', models.CharField(max_length=40)),
            ],
        ),
    ]
