# Generated by Django 3.2 on 2021-05-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportocrats', '0009_sports_equipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sports_equipments',
            name='equipment_name',
            field=models.CharField(default=1234, max_length=40),
            preserve_default=False,
        ),
    ]
