from django.contrib import admin

# Register your models here.
#from .models import Player_Male,cricket_male,football_male,basketball_male,chess_male,table_tennis_male,badminton_male,athletics_male,Player_female,admin_sports,cricket_female,football_female,basketball_female,chess_female,table_tennis_female,badminton_female,athletics_female
from .models import Player_Male,cricket_male,football_male,basketball_male,chess_male,table_tennis_male,badminton_male,athletics_male,Player_female,admin_sports,cricket_female,football_female,basketball_female,chess_female,table_tennis_female,badminton_female,athletics_female
#admin.site.register(Player_Male)
#admin.site.register(cricket_male)
#admin.site.register(football_male)
#admin.site.register(basketball_male)
#admin.site.register(chess_male)
#admin.site.register(table_tennis_male)
#admin.site.register(badminton_male)
#admin.site.register(athletics_male)
#admin.site.register(Player_female)
#admin.site.register(admin_sports)
#admin.site.register(cricket_female)
#admin.site.register(football_female)
#admin.site.register(basketball_female)
#admin.site.register(chess_female)
#admin.site.register(table_tennis_female)
#admin.site.register(badminton_female)
#admin.site.register(athletics_female)
admin.site.register(Player_Male)
admin.site.register(cricket_male)
admin.site.register(football_male)
admin.site.register(basketball_male)
admin.site.register(chess_male)
admin.site.register(table_tennis_male)
admin.site.register(badminton_male)
admin.site.register(athletics_male)
admin.site.register(Player_female)
admin.site.register(admin_sports)
admin.site.register(cricket_female)
admin.site.register(football_female)
admin.site.register(basketball_female)
admin.site.register(chess_female)
admin.site.register(table_tennis_female)
admin.site.register(badminton_female)
admin.site.register(athletics_female)
